[package]
name = "btreevec"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rand = "0.8.5"
trybuild = "1.0.56"
criterion = "0.3"

[profile.bench]
debug = true

[[bench]]
name = "get"
harness = false